### PR TITLE
Add dummy backend.

### PR DESCRIPTION
**Pull request by skorokithakis**
I've added a dummy backend that (probabilistically) never hits the limit, for testing/debugging.

### CODE REVIEW

**Comment by gmcquillan** [comment]
Very cool. I'll review today.

**Comment by gmcquillan** [comment]
Looks like one of the deps is no longer 2.6 compatible :(

**Comment by gmcquillan** [comment]
So, one issue is that the CacheBe "interface" includes ```count``` and ```limit``` functions because we limit not only based on IP, but also specific form values (e.g. usernames). How does your DummyCacheBe deal with those situations? Should it?

**Comment by skorokithakis** [comment]
Hmm, I don't use those, so I hadn't considered them. Blocking based on form values blocks based on those values, right? I.e. it blocks everyone who uses username foo, regardless of IP?

**Comment by gmcquillan** [comment]
Yeah, I could see the case for just not implementing them -- or always
returning random data for those as well (in the case of the limit function,
always returning false and an empty list).

**Comment by skorokithakis** [comment]
I've made the `limit` method always return the empty list, I'm not sure if that's appropriate, as I couldn't find much documentation on it. Let me know if it's not.

As for the tests, I don't know why they would be failing. This PR is about five lines long, and all it uses is `random.randrange`, which has been in the stdlib since 1.5.

**Comment by gmcquillan** [comment]
Yeah, I don't think it's your change that triggered the build to fail.

**Comment by gmcquillan** [comment]
Looks like Nose doesn't have a pegged version of Django, so it's getting
the latest, which breaks compatibility with 2.6. I think I'll just remove
the 2.6 coverage.

On Sat, Jun 27, 2015 at 12:32 PM, Gavin McQuillan <gavin.mcquillan@gmail.com
> wrote:

> Yeah, I don't think it's your change that triggered the build to fail.
>
> On Sat, Jun 27, 2015 at 10:52 AM, Stavros Korokithakis <

**Pull request merged**
