### PR TITLE
Closes #40: Django 2.1 and newer support

### LINKED ISSUE #40: Error with Django 2.1
Hello, I am getting a crash when using Django 2.1:

```
Traceback (most recent call last):
  File "/home/stavros/Code/Django/pastery/api/tests.py", line 44, in test_authenticated_posting
    content_type="application/x-www-form-urlencoded",
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/stavros/.virtualenvs/pastery/lib/python3.6/site-packages/brake/decorators.py", line 65, in _wrapped
    func_name = fn.__name__
AttributeError: 'functools.partial' object has no attribute '__name__'
```

Here's a [relevant post](https://stackoverflow.com/questions/52271368/django-2-1-functools-partial-object-has-no-attribute-name).

### PR DESCRIPTION
**Pull request by dqd**
Hello, this is a simple fix for `django-brake` to support recent Django versions.

### CODE REVIEW

**Comment by gmcquillan** [comment]
LGTM, do you mind adding Django 2.x to the tox.ini to help validate?

**Comment by dqd** [comment]
I do not mind at all, I just hope that you meant `.travis.yml`.

**Comment by gmcquillan** [comment]
Yep. .travis.yml. My mistake!

**Comment by gmcquillan** [comment]
I'll try and cut a release for pypi later today. Thanks for the help!

**Pull request merged**
